### ISSUE TITLE
SSH Portal support

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon-sync#44]
SSH Portal support should be available in Lagoon soon. Lagoon Sync doesn't yet support it.

I'd like to see support for the remote SSH Portal endpoints added to Lagoon CLI.

This is just a tracking issue which depends on https://github.com/uselagoon/lagoon-charts/pull/382

**Comment by timclifford** [comment]
PR #81

**Comment by rocketeerbkw** [comment]
Added in https://github.com/uselagoon/lagoon-sync/pull/112
