### ISSUE TITLE
DB backups should be automatically gzipped

### ISSUE THREAD

**Issue by cdchris12** [uselagoon/lagoon-sync#45]
All DB backups made using lagoon-sync should be gzipped by default. This lowers overall disk space required and data to be transferred.

**Comment by timclifford** [comment]
this has now been handled in #49 - https://github.com/uselagoon/lagoon-sync/pull/49/files#diff-e878532b16029079651ee820572fb5de1dd16c3b02ba0a877c8c26403bac48e7R144

**Comment by bomoko** [comment]
Closing this, it's done - thanks all
