### ISSUE TITLE
more efficient mysqldump

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon-sync#46]
`mysqldump` by default is quite slow an inefficient, we should research ways to make it more efficient, starting with what drush and lagoon backups do

**Comment by timclifford** [comment]
Started this by adding compression and output pipes through gzip, also added `--quick` option to reduce RAM impact on large tables.

https://github.com/uselagoon/lagoon-sync/pull/49/files#diff-e878532b16029079651ee820572fb5de1dd16c3b02ba0a877c8c26403bac48e7R146

**Comment by timclifford** [comment]
Closed with #49
