### ISSUE TITLE
Settle config load order of precedence 

### ISSUE THREAD

**Issue by bomoko** [uselagoon/lagoon-sync#65]
There seems to be some weirdness with the order that config files are loaded.

If I pass a config file into lagoon-sync, I expect that config to be the one that's used before every other possibility.

We need to settle this order to something like

1 - if config is passed as argument, it's used
2 - any local (to the project) .lagoon.yml (if the `lagoon-sync` section appears)
2 - Anything set in the `LAGOON_SYNC_DEFAULTS_PATH` and `LAGOON_SYNC_PATH` env var
3 - eventually - fall back on default to the app itself.

The relevant code seems to be here https://github.com/uselagoon/lagoon-sync/blob/main/cmd/root.go#L60-L121

**Comment by timclifford** [comment]
I can this work has been partly started in #66

**Comment by timclifford** [comment]
This one got tackled in #90
